export const ADD_REGISTER = "ADD_REGISTER";

export const AUTH_ERROR = "UTH_ERROR ";
export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const UPDATE_PROFILE = "UPDATE_PROFILE";

export const GET_LIST_PRODUCT = "GET_LIST_PRODUCT";
export const GET_PRODUCT_ID = "GET_PRODUCT_ID";

export const GET_LIST_PRODUCT_SELLER = "GET_LIST_PRODUCT_SELLER";
export const GET_PRODUCT_ID_SELLER = "GET_PRODUCT_ID_SELLER";

export const ADD_PRODUCT = "ADD_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";

export const GET_LIST_CATEGORY = "GET_LIST_CATEGORY";

export const GET_LIST_SIZE = "GET_LIST_SIZE";
export const ADD_SIZE = "ADD_SIZE";
export const DETAIL_SIZE = "DETAIL_SIZE";
export const UPDATE_SIZE = "UPDATE_SIZE";
export const DELETE_SIZE = "DELETE_SIZE";

export const WISHLIST_SELLER = "WISHLIST_SELLER";
export const WISHLIST_BUYER = "WISHLIST_BUYER";
export const ADD_WISHLIST_BUYER = "ADD_WISHLIST_BUYER";
export const DELETE_WISHLIST_BUYER = "DELETE_WISHLIST_BUYER";

export const GET_LIST_TRANSACTION_BUYER = "GET_LIST_TRANSACTION_BUYER";
export const GET_LIST_TRANSACTION_SELLER = "GET_LIST_TRANSACTION_SELLER";
export const GET_TRANSACTION_ID_SELLER = "GET_TRANSACTION_ID_SELLER";
export const ADD_TRANSACTION = "ADD_TRANSACTION";
export const UPDATE_TRANSACTION_SELLER = "UPDATE_TRANSACTION_SELLER";

export const NOTIFICATION_BUYER = "NOTIFICATION_BUYER";
export const NOTIFICATION_SELLER = "NOTIFICATION_SELLER";
export const UPDATE_NOTIFICATION_BUYER = "UPDATE_NOTIFICATION_BUYER";
export const UPDATE_NOTIFICATION_SELLER = "UPDATE_NOTIFICATION_SELLER";

export const GET_PROVINSI = "GET_PROVINSI";
export const GET_KOTA = "GET_KOTA";
