export const GET_LIST_PRODUCT = "GET_LIST_PRODUCT";
export const GET_PRODUCT_ID = "GET_PRODUCT_ID";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";

export const ADD_REGISTER = "ADD_REGISTER";
